//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DriveSync.RC
//


#define IDD_ABOUTBOX				100
#define IDR_MAINFRAME				128
//#define IDR_DRIVESYNCTYPE	129
#define IDD_MAINDLG					129
#define IDD_OPTION					130
#define IDC_TRANSACTIONVIEWPOS		1000
#define IDC_LIST_LOG				1001
#define IDC_BUTTON_OPTION			1002
#define IDC_BUTTON_OPENSYNCFOLDER	1003
#define IDC_BUTTON_FOLDERSELECT		1004
#define IDC_EDIT_SYNCFOLDERPAHT		1005
#define IDC_CHECKBOX_AUTOSYNC		1006
#define IDC_BUTTON_LOGIN			1007
#define IDC_EDIT_MAIL				1008
#define IDC_EDIT_PASS				1009
#define IDC_STATIC_STRAGEINFO		1010
#define IDC_COMBO_MEGAFOLDER		1011
#define IDC_EDIT_DLTARGETFOLDER		1012
#define IDC_BUTTON_DLSTART			1013
#define IDC_BUTTON_DLFOLDERSELECT	1014
#define IDC_COMBO_EXCLUDEEXT		1015
#define IDC_BUTTON_ADDEXCLUDEEXT	1016
#define IDC_BUTTON_REMOVEEXCLUDEEXT	1017
#define IDC_EDIT_MAXUPCOUNT			1018
#define IDC_SPIN_MAXUPCOUNT			1019
#define IDC_EDIT_MAXDOWNCOUNT		1020
#define IDC_SPIN_MAXDOWNCOUNT		1021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	201
#define _APS_NEXT_CONTROL_VALUE		1500
#define _APS_NEXT_SYMED_VALUE		150
#define _APS_NEXT_COMMAND_VALUE		32775
#endif
#endif
